apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  replicas: 4
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: 192.168.10.227:8085/eureka-project:$CI_COMMIT_SHORT_SHA
        #imagePullPolicy: IfNotPresent  # Add this line to specify the imagePullPolicy
        ports:
        - containerPort: 8761
      imagePullSecrets:
      - name: regcred

